spring:
  application:
    name: user-roles-client
  security:
    oauth2.client:
      provider:
        keycloak.issuer-uri: http://127.0.0.1:9090/realms/user-roles-realm
      registration.kc-oidc:
        provider: keycloak
        client-name: User and Roles
        client-id: user-roles
        client-secret: 077US8gFeWfMWiPa2sMM28J5VOl7EQuw
        authorization-grant-type: authorization_code
        scope:
          - openid
          - email
          - profile

server:
  port: 4200

user-roles:
  resource:
    url: http://localhost:8080/kc


logging:
  level:
    web: trace
    org.springframework.web.client: trace
